### PR TITLE
Cu-1yuej41 add animated rainbow border to popup component 

### PR DESCRIPTION
**Pull request by HenryQuillin**

### CODE REVIEW

**Comment by j-mateo** [comment]
Task linked: [CU-1yuej41 Add Rainbow Border](https://app.clickup.com/t/1yuej41)

**Comment by HenryQuillin** [comment]
> Visit the preview URL for this PR (updated for commit [ff8d15f](https://github.com/projectNEWM/newm-artist-portal/commit/ff8d15f57cb01c6efb6c055ac6493edd385d9f20)):
> 
> https://newm-artist-portal--pr22-cu-1yuej41-add-rainb-6dywx0qt.web.app
> 
> (expires Sat, 12 Feb 2022 17:07:05 GMT)
> 
> 🔥 via [Firebase Hosting GitHub Action](https://github.com/marketplace/actions/deploy-to-firebase-hosting) 🌎

Hmm... The fonts arent loading in the firebase preview @j-mateo

**Review by j-mateo — APPROVED** [review]
Wow this looks really good! 🔥

**Comment by HenryQuillin** [comment]
> 


> > Visit the preview URL for this PR (updated for commit [ff8d15f](https://github.com/projectNEWM/newm-artist-portal/commit/ff8d15f57cb01c6efb6c055ac6493edd385d9f20)):
> > https://newm-artist-portal--pr22-cu-1yuej41-add-rainb-6dywx0qt.web.app
> > (expires Sat, 12 Feb 2022 17:07:05 GMT)
> > 🔥 via [Firebase Hosting GitHub Action](https://github.com/marketplace/actions/deploy-to-firebase-hosting) 🌎
> 
> Hmm... The fonts arent loading in the firebase preview @j-mateo
Wait nevermind. WOrked once I refreshed

**Pull request merged**
